import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import layout from "@/components/layout/layout";
import Navbar from "@/components/navbar/navbar";
import Descripcion from "@/components/descripcion/descripcion";
import QuienesSomos from "@/components/quines_somos/quienesSomos";
import Footer from "@/components/footer/footer";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <link
          href="https://unpkg.com/aos@2.3.1/dist/aos.css"
          rel="stylesheet"
        />
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/img/icono.jpeg" />
      </Head>
      <div className={styles.body}>
        <Navbar></Navbar>
        <Descripcion></Descripcion>
        <QuienesSomos></QuienesSomos>
        <Footer></Footer>
        <script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
      </div>
    </>
  );
}
